cc_library(
    name = 'add_lib',
    hdrs = ['src/add.hpp'],
    visibility = ["//visibility:public"],
)

cc_library(
    name = 'mul_lib',
    hdrs = ['src/mul.hpp'],
    srcs = ['src/mul.cpp'],
    linkstatic = True,
    visibility = ["//visibility:public"],
)
